#!/usr/bin/expect -f

set timeout 15
set uuid "5a0d6a15-b664-4304-8530-3a0ec53e5bc1"

spawn /usr/bin/btmgmt

expect -re {\[mgmt\].*>}

send "power on\r"
expect -re {\[mgmt\].*>}

send "le on\r"
expect -re {\[mgmt\].*>}

send "name SCOREOS\r"
expect -re {\[mgmt\].*>}

send "connectable on\r"
expect -re {\[mgmt\].*>}

send "advertising off\r"
expect -re {\[mgmt\].*>}

send "clr-adv\r"
expect -re {\[mgmt\].*>}

send "add-adv -c -g -n -u $uuid 1\r"

expect {
    -re {Instance added: 1} {}
    timeout {
        puts "Failed to add SCOREOS advertisement"
        exit 1
    }
}

expect -re {\[mgmt\].*>}

send "advinfo\r"

expect {
    -re {Instances list with 1 item} {}
    timeout {
        puts "Advertisement was not verified"
        exit 1
    }
}

expect -re {\[mgmt\].*>}

send "quit\r"
expect eof

puts "SCOREOS Bluetooth advertisement started."
exit 0
